/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Dao.CaixaJPA;
import Dao.ClienteJPA;
import Dao.ProdutoJPA;
import Model.Caixa;
import Model.Cliente;
import Model.Produto;
import Model.Usuario;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kikut
 */
public class CaixaView extends javax.swing.JFrame {
    
     public CaixaView(Usuario u) {
        initComponents(); 
        
        if (u == null || u.getCargo() == null) {
            return;
        }
        
        if(u.getCargo().equalsIgnoreCase("Gerente")) {
            excluirJB.setEnabled(true);
            finalizarJB.setEnabled(true);
            adicionarJB.setEnabled(true);
        } else if (u.getCargo().equalsIgnoreCase("Artista")) {
            excluirJB.setEnabled(false);
            finalizarJB.setEnabled(false);
            adicionarJB.setEnabled(false);
        } else {
            excluirJB.setEnabled(true);
            finalizarJB.setEnabled(true);
            adicionarJB.setEnabled(true);
        }
    }
    
    private double valorTotalGeral = 0.0;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CaixaView.class.getName());

    /**
     * Creates new form Caixa
     */
    public CaixaView() {
        initComponents();
        carregarDadosTela();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbProduto = new javax.swing.JComboBox();
        sQuantidade = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        excluirJB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        adicionarJB = new javax.swing.JButton();
        lblValorTotal = new javax.swing.JLabel();
        finalizarJB = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cbMetodo = new javax.swing.JComboBox();
        vendasJB = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        cbCliente = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(249, 249, 249));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CAIXA");

        cbProduto.setBackground(new java.awt.Color(64, 67, 68));
        cbProduto.setForeground(new java.awt.Color(211, 211, 211));
        cbProduto.addActionListener(this::cbProdutoActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Adicionar Produto:");

        excluirJB.setBackground(new java.awt.Color(102, 0, 0));
        excluirJB.setForeground(new java.awt.Color(211, 211, 211));
        excluirJB.setText("excluir");
        excluirJB.addActionListener(this::excluirJBActionPerformed);

        jScrollPane2.setBackground(new java.awt.Color(227, 242, 249));
        jScrollPane2.setForeground(new java.awt.Color(51, 51, 51));

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "nome", "quantidade", "preço unitário", "subtotal"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jScrollPane1.setViewportView(jScrollPane2);

        adicionarJB.setBackground(new java.awt.Color(0, 102, 0));
        adicionarJB.setForeground(new java.awt.Color(211, 211, 211));
        adicionarJB.setText("adicionar");
        adicionarJB.addActionListener(this::adicionarJBActionPerformed);

        lblValorTotal.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblValorTotal.setForeground(new java.awt.Color(51, 51, 51));
        lblValorTotal.setText("Valor Total : 0,00");

        finalizarJB.setBackground(new java.awt.Color(153, 153, 153));
        finalizarJB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        finalizarJB.setForeground(new java.awt.Color(51, 51, 51));
        finalizarJB.setText("Finalizar");
        finalizarJB.addActionListener(this::finalizarJBActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Método de pagamento :");

        cbMetodo.setBackground(new java.awt.Color(64, 67, 68));
        cbMetodo.setForeground(new java.awt.Color(211, 211, 211));
        cbMetodo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        vendasJB.setBackground(new java.awt.Color(65, 67, 68));
        vendasJB.setForeground(new java.awt.Color(211, 211, 211));
        vendasJB.setText("vendas concluídas");
        vendasJB.addActionListener(this::vendasJBActionPerformed);

        jButton5.setBackground(new java.awt.Color(102, 0, 0));
        jButton5.setForeground(new java.awt.Color(211, 211, 211));
        jButton5.setText("Voltar");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        cbCliente.setBackground(new java.awt.Color(64, 67, 68));
        cbCliente.setForeground(new java.awt.Color(211, 211, 211));
        cbCliente.addActionListener(this::cbClienteActionPerformed);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Cliente:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblValorTotal)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(finalizarJB, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(adicionarJB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(excluirJB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vendasJB, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(14, 14, 14)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(adicionarJB)
                        .addComponent(excluirJB)
                        .addComponent(vendasJB))
                    .addComponent(sQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(finalizarJB)
                    .addComponent(jButton5))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbProdutoActionPerformed

    private void excluirJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirJBActionPerformed
      int linhaSelecionada = jTable1.getSelectedRow();

    if (linhaSelecionada == -1) {
    JOptionPane.showMessageDialog(this, "Selecione um item na tabela para excluir.");
    return;
}


    int idReal = Integer.parseInt(jTable1.getValueAt(linhaSelecionada, 0).toString());

    int resposta = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir este produto?", "Confirmação", JOptionPane.YES_NO_OPTION);
    if (resposta == JOptionPane.YES_OPTION) {
    try {
        ClienteJPA.removerCliente(idReal);
        
        JOptionPane.showMessageDialog(this, "Produto excluído com sucesso!");
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao excluir: " + e.getMessage());
    }
}
    }//GEN-LAST:event_excluirJBActionPerformed

    private void adicionarJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarJBActionPerformed
        try {
        
        Produto produtoSelecionado = (Produto) cbProduto.getSelectedItem(); 
        
        if (produtoSelecionado == null) {
            JOptionPane.showMessageDialog(this, "Por favor, selecione um produto!");
            return;
        }

        
        int quantidade = (int) sQuantidade.getValue();
        if (quantidade <= 0) {
            JOptionPane.showMessageDialog(this, "A quantidade deve ser maior do que zero!");
            return;
        }

        
        double precoUnitario = produtoSelecionado.getPreco(); 
        double subtotalLinha = quantidade * precoUnitario;

        DefaultTableModel modeloLocal = (DefaultTableModel) jTable1.getModel();
        
        Object[] novaLinha = {
            produtoSelecionado.getIdProduto(),
            produtoSelecionado.getNome(),
            quantidade,
            String.format("%.2f", precoUnitario),
            String.format("%.2f", subtotalLinha)
        };
        
        modeloLocal.addRow(novaLinha);

        this.valorTotalGeral += subtotalLinha;

        lblValorTotal.setText("Total: R$ " + String.format("%.2f", this.valorTotalGeral));

        sQuantidade.setValue(1);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao adicionar item: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_adicionarJBActionPerformed

    private void finalizarJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarJBActionPerformed
       
     String metodoPagamento = cbMetodo.getSelectedItem().toString();
    if (metodoPagamento == null) {
    JOptionPane.showMessageDialog(this, "Por favor, selecione um método!");
    return; 
    }
    
    Cliente clienteSelecionado = (Cliente) cbCliente.getSelectedItem();
    if (clienteSelecionado == null) {
    JOptionPane.showMessageDialog(this, "Por favor, selecione um cliente!");
    return; 
    }

    Produto produtoSelecionado = (Produto) cbProduto.getSelectedItem();

    if (produtoSelecionado == null) {
    JOptionPane.showMessageDialog(this, "Por favor, selecione um produto!");
    return; 
    }

    double valorFinal = this.valorTotalGeral;
    
    Produto produto = (Produto) cbProduto.getSelectedItem();
            int qtdUsada = (int) sQuantidade.getValue();

            produto.consumirMaterial(qtdUsada); 

            ProdutoJPA.atualizarProdutosJPQL(
            produto.getIdProduto(), 
            produto.getNome(), 
            produto.getArtista(), 
            produto.getPreco(),
            produto.getCategoria(),
            produto.getEstoqueP()
            );
    
    
    Caixa caixa = new Caixa(0, valorFinal, metodoPagamento, clienteSelecionado, produtoSelecionado);
            CaixaJPA.cadastrar(caixa);
            
             DefaultTableModel modeloLocal = (DefaultTableModel) jTable1.getModel();
            modeloLocal.setRowCount(0); 
        
            this.valorTotalGeral = 0.0; 
            lblValorTotal.setText("Total: R$ 0,00");

            JOptionPane.showMessageDialog(this, "Cadastro cadastrada com sucesso!");
    }//GEN-LAST:event_finalizarJBActionPerformed

    private void cbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbClienteActionPerformed

    private void vendasJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendasJBActionPerformed
        ConsultaCaixa cc = new ConsultaCaixa();
        cc.setVisible(true);
    }//GEN-LAST:event_vendasJBActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

   public void carregarDadosTela() {
    try {
       
        List<Produto> produto = ProdutoJPA.filtrarTodos();
        cbProduto.removeAllItems();
        for (Produto p : produto) {
            cbProduto.addItem(p);
        }
        
        List<Cliente> cliente = ClienteJPA.filtrarTodos();
        cbCliente.removeAllItems(); 
        for (Cliente c : cliente) {
            cbCliente.addItem(c); 
        }
        
         List<Caixa> caixa = CaixaJPA.filtrarTodos();
        cbMetodo.removeAllItems(); 
        for (Caixa c : caixa) {
            cbMetodo.addItem(c); 
        }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao carregar dados da tela: " + e.getMessage());
    }
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CaixaView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarJB;
    private javax.swing.JComboBox cbCliente;
    private javax.swing.JComboBox cbMetodo;
    private javax.swing.JComboBox cbProduto;
    private javax.swing.JButton excluirJB;
    private javax.swing.JButton finalizarJB;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JSpinner sQuantidade;
    private javax.swing.JButton vendasJB;
    // End of variables declaration//GEN-END:variables
}
