/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Dao.ConexaoJPA;
import Dao.UsuarioJPA;
import Model.Usuario;
import jakarta.persistence.EntityManager;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kikut
 */
public class ConsultaUsuario extends javax.swing.JFrame {
    
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConsultaUsuario.class.getName());

    /**
     * Creates new form ConsultaUsuario
     */
    public ConsultaUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        VoltarJB = new javax.swing.JButton();
        cadastrarJB = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        TFpesquisar = new javax.swing.JTextField();
        pesquisarJB = new javax.swing.JButton();
        atualizarJB = new javax.swing.JButton();
        excluirJB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(249, 249, 249));

        jScrollPane1.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setForeground(new java.awt.Color(249, 249, 249));

        jTable1.setBackground(new java.awt.Color(61, 64, 66));
        jTable1.setForeground(new java.awt.Color(211, 211, 211));
        jTable1.setModel(montarTabela(UsuarioJPA.filtrarTodos()));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Usuários Cadastrados");

        VoltarJB.setBackground(new java.awt.Color(102, 0, 0));
        VoltarJB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        VoltarJB.setForeground(new java.awt.Color(255, 153, 153));
        VoltarJB.setText("Voltar");
        VoltarJB.addActionListener(this::VoltarJBActionPerformed);

        cadastrarJB.setText("Cadastrar Usuário");
        cadastrarJB.addActionListener(this::cadastrarJBActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Pesquisar usuário :");

        pesquisarJB.setText("Pesquisar");
        pesquisarJB.addActionListener(this::pesquisarJBActionPerformed);

        atualizarJB.setBackground(new java.awt.Color(0, 51, 102));
        atualizarJB.setText("atualizar");
        atualizarJB.addActionListener(this::atualizarJBActionPerformed);

        excluirJB.setBackground(new java.awt.Color(102, 0, 0));
        excluirJB.setText("excluir");
        excluirJB.addActionListener(this::excluirJBActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(VoltarJB, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(excluirJB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(atualizarJB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cadastrarJB))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TFpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pesquisarJB)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TFpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesquisarJB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(atualizarJB)
                        .addComponent(excluirJB))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(VoltarJB)
                        .addComponent(cadastrarJB)))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarJBActionPerformed
        this.dispose();
    }//GEN-LAST:event_VoltarJBActionPerformed

    private void pesquisarJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarJBActionPerformed
         List<Usuario> listaFiltrada = UsuarioJPA.filtrarPorPesquisa(TFpesquisar.getText());
        jTable1.setModel(montarTabela(listaFiltrada));
        jScrollPane1.setViewportView(jTable1);
    }//GEN-LAST:event_pesquisarJBActionPerformed

    private void atualizarJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarJBActionPerformed
        int linhaSelecionada = jTable1.getSelectedRow();
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um item na tabela para atualizar.");
            return;
        }
         try {
            
        if (jTable1.isEditing()) {
         jTable1.getCellEditor().stopCellEditing();
        }
        
        try {
            
    int id = Integer.parseInt(jTable1.getValueAt(linhaSelecionada, 0).toString());
    String login = jTable1.getValueAt(linhaSelecionada, 1).toString();
    String senha = jTable1.getValueAt(linhaSelecionada, 2).toString();
    String cargo = jTable1.getValueAt(linhaSelecionada, 3).toString();
  
    
    
    
    
    UsuarioJPA jpaInstancia = new UsuarioJPA(); 
    jpaInstancia.atualizarUsuarioJPQL(id, login, senha, cargo);
    
   EntityManager managerTela = ConexaoJPA.conectar();
    
    managerTela.clear(); 
    
    List<Usuario> listaAtualizada = managerTela.createQuery("FROM Usuario", Usuario.class).getResultList();
    
    jTable1.setModel(montarTabela(listaAtualizada)); 
    
    managerTela.close();

    JOptionPane.showMessageDialog(null, "Dados atualizados com sucesso!");

    }                                        
     catch (Exception e) {
         System.out.println("Erro ao atualizar dados: " + e.getMessage());
    }
    }catch (Exception e) {
         System.out.println("Erro ao atualizar: " + e.getMessage());
    }
    }//GEN-LAST:event_atualizarJBActionPerformed

    private void excluirJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirJBActionPerformed
      int linhaSelecionada = jTable1.getSelectedRow();

    if (linhaSelecionada == -1) {
    JOptionPane.showMessageDialog(this, "Selecione um item na tabela para excluir.");
    return;
}


    int idReal = Integer.parseInt(jTable1.getValueAt(linhaSelecionada, 0).toString());

    int resposta = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir?", "Confirmação", JOptionPane.YES_NO_OPTION);
    if (resposta == JOptionPane.YES_OPTION) {
    try {
        UsuarioJPA.removerProduto(idReal);
        
        JOptionPane.showMessageDialog(this, "excluído com sucesso!");
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao excluir: " + e.getMessage());
    }
}
    }//GEN-LAST:event_excluirJBActionPerformed

    private void cadastrarJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarJBActionPerformed
        CadastroUsuario cu = new CadastroUsuario(this);
        cu.setVisible(true);
    }//GEN-LAST:event_cadastrarJBActionPerformed

     public DefaultTableModel montarTabela(List<Usuario> lista) {
         
          DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        
        String[] colunas = {"ID", "login", "senha", "cargo"};
        DefaultTableModel tabela = new DefaultTableModel();
        tabela.setColumnIdentifiers(colunas);
        
         if (lista == null || lista.isEmpty()) {
        return tabela; 
    }
        
        
        for (int i = 0; i < lista.size(); i++) { 
        Usuario u = lista.get(i);
        
       
                 Object[] linha = {
                u.getIdUsuario(), 
                u.getLogin(),
                u.getSenha(),
                u.getCargo()
        };
            tabela.addRow(linha);
        }
        return tabela;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ConsultaUsuario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TFpesquisar;
    private javax.swing.JButton VoltarJB;
    private javax.swing.JButton atualizarJB;
    private javax.swing.JButton cadastrarJB;
    private javax.swing.JButton excluirJB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton pesquisarJB;
    // End of variables declaration//GEN-END:variables
}
