/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Dao.ClienteJPA;
import Model.Cliente;
import Model.Usuario;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kikut
 */
public class ConsultaCliente extends javax.swing.JFrame {
    
     public ConsultaCliente(Usuario u) {
        initComponents(); 
        
        if (u == null || u.getCargo() == null) {
            return;
        }
        
        if(u.getCargo().equalsIgnoreCase("Gerente")) {
            pesquisarJB.setEnabled(true);
            excluirJB.setEnabled(true);
            atualizarJB.setEnabled(true);
            cadastrarJB.setEnabled(true);
        } else if (u.getCargo().equalsIgnoreCase("Artista")) {
            pesquisarJB.setEnabled(true);
            excluirJB.setEnabled(false);
            atualizarJB.setEnabled(false);
            cadastrarJB.setEnabled(true);
        } else {
            pesquisarJB.setEnabled(true);
            excluirJB.setEnabled(false);
            atualizarJB.setEnabled(false);
            cadastrarJB.setEnabled(false);
        }
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConsultaCliente.class.getName());

    /**
     * Creates new form ConsultaCliente
     */
    public ConsultaCliente() {
        initComponents();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TFpesquisar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pesquisarJB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        VoltarJB = new javax.swing.JButton();
        cadastrarJB = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        atualizarJB = new javax.swing.JButton();
        excluirJB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(230, 242, 249));

        TFpesquisar.addActionListener(this::TFpesquisarActionPerformed);

        jScrollPane1.setBackground(new java.awt.Color(227, 242, 249));
        jScrollPane1.setForeground(new java.awt.Color(51, 51, 51));

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setForeground(new java.awt.Color(51, 51, 51));
        jTable1.setModel(montarTabela(ClienteJPA.filtrarTodos()));
        jScrollPane1.setViewportView(jTable1);

        pesquisarJB.setText("Pesquisar");
        pesquisarJB.addActionListener(this::pesquisarJBActionPerformed);

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Clientes Cadastrados");

        VoltarJB.setBackground(new java.awt.Color(102, 0, 0));
        VoltarJB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        VoltarJB.setForeground(new java.awt.Color(255, 153, 153));
        VoltarJB.setText("Voltar");
        VoltarJB.addActionListener(this::VoltarJBActionPerformed);

        cadastrarJB.setText("Cadastrar Cliente");
        cadastrarJB.addActionListener(this::cadastrarJBActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Pesquisar cliente :");

        atualizarJB.setBackground(new java.awt.Color(0, 51, 102));
        atualizarJB.setForeground(new java.awt.Color(249, 249, 249));
        atualizarJB.setText("atualizar");
        atualizarJB.addActionListener(this::atualizarJBActionPerformed);

        excluirJB.setBackground(new java.awt.Color(102, 0, 0));
        excluirJB.setForeground(new java.awt.Color(249, 249, 249));
        excluirJB.setText("excluir");
        excluirJB.addActionListener(this::excluirJBActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TFpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pesquisarJB)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(VoltarJB, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(excluirJB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(atualizarJB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cadastrarJB)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TFpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesquisarJB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(atualizarJB)
                        .addComponent(excluirJB))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(VoltarJB)
                        .addComponent(cadastrarJB)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarJBActionPerformed
        this.dispose();
    }//GEN-LAST:event_VoltarJBActionPerformed

    private void cadastrarJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarJBActionPerformed
        CadastroCliente c = new CadastroCliente(this);
        c.setVisible(true);
    }//GEN-LAST:event_cadastrarJBActionPerformed

    private void atualizarJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarJBActionPerformed
                int linhaSelecionada = jTable1.getSelectedRow();
        
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um cliente na tabela para atualizar.");
            return;
        }
         try {
             
        if (jTable1.isEditing()) {
         jTable1.getCellEditor().stopCellEditing();
        }
        
        try {
        Cliente c = new Cliente();
        int id = Integer.parseInt(jTable1.getValueAt(linhaSelecionada, 0).toString());
        String nome = jTable1.getValueAt(linhaSelecionada, 1).toString();
        String celular = jTable1.getValueAt(linhaSelecionada, 2).toString();
        String email = jTable1.getValueAt(linhaSelecionada, 3).toString();
        String dataN = jTable1.getValueAt(linhaSelecionada, 4).toString();

        String dataProntaParaOBanco = null;

        
        if (dataN != null && !dataN.equals("Não informada") && !dataN.trim().isEmpty()) {
        dataProntaParaOBanco = ClienteJPA.converterParaSQL(dataN);
        
        }
        ClienteJPA dao = new ClienteJPA();
        dao.atualizarClienteJPQL(id, nome, celular, email, dataProntaParaOBanco); 
        
        
        
        JOptionPane.showMessageDialog(this, "Cliente atualizado com sucesso!");
         }catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao atualizar dados: "+ e.getMessage());
     }   //JOptionPane.showMessageDialog
        }catch (Exception e) {
             JOptionPane.showMessageDialog(this, "Erro ao atualizar: "+ e.getMessage());
    }//GEN-LAST:event_atualizarJBActionPerformed
    }
    private void excluirJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirJBActionPerformed
         int linhaSelecionada = jTable1.getSelectedRow();

    if (linhaSelecionada == -1) {
    JOptionPane.showMessageDialog(this, "Selecione um cliente na tabela para excluir.");
    return;
}


    int idReal = Integer.parseInt(jTable1.getValueAt(linhaSelecionada, 0).toString());

    int resposta = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir este cliente?", "Confirmação", JOptionPane.YES_NO_OPTION);
    if (resposta == JOptionPane.YES_OPTION) {
    try {
        ClienteJPA.removerCliente(idReal);
        
        JOptionPane.showMessageDialog(this, "Cliente excluído com sucesso!");
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao excluir: " + e.getMessage());
    }
}
    }//GEN-LAST:event_excluirJBActionPerformed

    private void pesquisarJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarJBActionPerformed
        List<Cliente> listaFiltrada = ClienteJPA.filtrarPorPesquisa(TFpesquisar.getText());
        jTable1.setModel(montarTabela(listaFiltrada));
        jScrollPane1.setViewportView(jTable1);
    }//GEN-LAST:event_pesquisarJBActionPerformed

    private void TFpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFpesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFpesquisarActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        jTable1.setModel(montarTabela(ClienteJPA.filtrarTodos()));
        jScrollPane1.setViewportView(jTable1);
    }//GEN-LAST:event_formWindowGainedFocus

    public DefaultTableModel montarTabela(List<Cliente> lista) {
        
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        
        String[] colunas = {"ID", "nome", "celular", "email", "data de nascimento"};
        DefaultTableModel tabela = new DefaultTableModel();
        tabela.setColumnIdentifiers(colunas);
        
         if (lista == null || lista.isEmpty()) {
        return tabela; 
    }
        
        
        for (int i = 0; i < lista.size(); i++) { 
        Cliente c = lista.get(i);
        
        String dataStr = "Não informada";
        if (c.getDataNascimento() != null) {
            dataStr = c.getDataNascimento().toString(); 
        }
            
                 Object[] linha = {
                c.getIdCliente(), 
                c.getNome(),
                c.getCelular(),
                c.getEmail(),
                dataStr
        };
            tabela.addRow(linha);
        }
        return tabela;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ConsultaCliente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TFpesquisar;
    private javax.swing.JButton VoltarJB;
    private javax.swing.JButton atualizarJB;
    private javax.swing.JButton cadastrarJB;
    private javax.swing.JButton excluirJB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton pesquisarJB;
    // End of variables declaration//GEN-END:variables
}
