/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Dao.ConexaoJPA;
import Dao.ProdutoJPA;
import Model.Produto;
import Model.Usuario;
import View.CadastroProduto;
import jakarta.persistence.EntityManager;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kikut
 */
public class ConsultaProduto extends javax.swing.JFrame {
    
    public ConsultaProduto(Usuario u) {
        initComponents(); 
        
        if (u == null || u.getCargo() == null) {
            return;
        }
        
        if(u.getCargo().equalsIgnoreCase("Gerente")) {
            pesquisarJB.setEnabled(true);
            excluirJB.setEnabled(true);
            atualizarJB.setEnabled(true);
            cadastrarJB.setEnabled(true);
        } else if (u.getCargo().equalsIgnoreCase("Artista")) {
            pesquisarJB.setEnabled(true);
            excluirJB.setEnabled(true);
            atualizarJB.setEnabled(true);
            cadastrarJB.setEnabled(true);
        } else {
            pesquisarJB.setEnabled(true);
            excluirJB.setEnabled(false);
            atualizarJB.setEnabled(false);
            cadastrarJB.setEnabled(false);
        }
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConsultaProduto.class.getName());

    /**
     * Creates new form ConsultaProduto
     */
    public ConsultaProduto() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TFpesquisar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pesquisarJB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        VoltarJB = new javax.swing.JButton();
        cadastrarJB = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        atualizarJB = new javax.swing.JButton();
        excluirJB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(54, 56, 58));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(230, 242, 249));

        jTable1.setBackground(new java.awt.Color(61, 64, 66));
        jTable1.setForeground(new java.awt.Color(211, 211, 211));
        jTable1.setModel(montarTabela(ProdutoJPA.filtrarTodos()));
        jScrollPane1.setViewportView(jTable1);

        pesquisarJB.setText("Pesquisar");
        pesquisarJB.addActionListener(this::pesquisarJBActionPerformed);

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Produtos Cadastrados");

        VoltarJB.setBackground(new java.awt.Color(102, 0, 0));
        VoltarJB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        VoltarJB.setForeground(new java.awt.Color(255, 153, 153));
        VoltarJB.setText("Voltar");
        VoltarJB.addActionListener(this::VoltarJBActionPerformed);

        cadastrarJB.setText("Cadastrar Produto");
        cadastrarJB.addActionListener(this::cadastrarJBActionPerformed);

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Pesquisar produto :");

        atualizarJB.setBackground(new java.awt.Color(0, 51, 102));
        atualizarJB.setText("atualizar");
        atualizarJB.addActionListener(this::atualizarJBActionPerformed);

        excluirJB.setBackground(new java.awt.Color(102, 0, 0));
        excluirJB.setText("excluir");
        excluirJB.addActionListener(this::excluirJBActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TFpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pesquisarJB)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(VoltarJB, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(excluirJB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(atualizarJB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cadastrarJB)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TFpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesquisarJB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(atualizarJB)
                        .addComponent(excluirJB))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(VoltarJB)
                        .addComponent(cadastrarJB)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarJBActionPerformed
        this.dispose();
    }//GEN-LAST:event_VoltarJBActionPerformed

    private void atualizarJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarJBActionPerformed
         int linhaSelecionada = jTable1.getSelectedRow();
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um item na tabela para atualizar.");
            return;
        }
         try {
            
        if (jTable1.isEditing()) {
         jTable1.getCellEditor().stopCellEditing();
        }
        
        try {
            
    int id = Integer.parseInt(jTable1.getValueAt(linhaSelecionada, 0).toString());
    String nome = jTable1.getValueAt(linhaSelecionada, 1).toString();
    String artista = jTable1.getValueAt(linhaSelecionada, 2).toString();
    double preco = Double.parseDouble(jTable1.getValueAt(linhaSelecionada, 3).toString().replace(",", "."));
    String categoria = jTable1.getValueAt(linhaSelecionada, 4).toString();
    int estoque =  Integer.parseInt (jTable1.getValueAt(linhaSelecionada, 5).toString());
    
    
    
    
    ProdutoJPA jpaInstancia = new ProdutoJPA(); 
    jpaInstancia.atualizarProdutosJPQL(id, nome, artista, preco, categoria, estoque);
    
   EntityManager managerTela = ConexaoJPA.conectar();
    
    managerTela.clear(); 
    
    List<Produto> listaAtualizada = managerTela.createQuery("FROM Produto", Produto.class).getResultList();
    
    jTable1.setModel(montarTabela(listaAtualizada)); 
    
    managerTela.close();

    JOptionPane.showMessageDialog(null, "Dados atualizados com sucesso!");

    }                                        
     catch (Exception e) {
         System.out.println("Erro ao atualizar dados: " + e.getMessage());
    }
    }catch (Exception e) {
         System.out.println("Erro ao atualizar: " + e.getMessage());
    }        
    }//GEN-LAST:event_atualizarJBActionPerformed

    private void excluirJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirJBActionPerformed
             int linhaSelecionada = jTable1.getSelectedRow();

    if (linhaSelecionada == -1) {
    JOptionPane.showMessageDialog(this, "Selecione um item na tabela para excluir.");
    return;
}


    int idReal = Integer.parseInt(jTable1.getValueAt(linhaSelecionada, 0).toString());

    int resposta = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir?", "Confirmação", JOptionPane.YES_NO_OPTION);
    if (resposta == JOptionPane.YES_OPTION) {
    try {
        ProdutoJPA.removerProduto(idReal);
        
        JOptionPane.showMessageDialog(this, "excluído com sucesso!");
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao excluir: " + e.getMessage());
    }
}
    }//GEN-LAST:event_excluirJBActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        jTable1.setModel(montarTabela(ProdutoJPA.filtrarTodos()));
        jScrollPane1.setViewportView(jTable1);
    }//GEN-LAST:event_formWindowGainedFocus

    private void pesquisarJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarJBActionPerformed
        List<Produto> listaFiltrada = ProdutoJPA.filtrarPorPesquisa(TFpesquisar.getText());
        jTable1.setModel(montarTabela(listaFiltrada));
        jScrollPane1.setViewportView(jTable1);
    }//GEN-LAST:event_pesquisarJBActionPerformed

    private void cadastrarJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarJBActionPerformed
       CadastroProduto c = new CadastroProduto(this);
       c.setVisible(true);
    }//GEN-LAST:event_cadastrarJBActionPerformed

    
    public DefaultTableModel montarTabela(List<Produto> lista) {
        
         DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        
        String[] colunas = {"ID", "nome", "artista", "preco", "categoria", "estoqueP"};
        DefaultTableModel tabela = new DefaultTableModel();
        tabela.setColumnIdentifiers(colunas);
        
         if (lista == null || lista.isEmpty()) {
        return tabela; 
    }
        
        
        for (int i = 0; i < lista.size(); i++) { 
        Produto p = lista.get(i);
        
       
                 Object[] linha = {
                p.getIdProduto(), 
                p.getNome(),
                p.getArtista(),
                Double.toString (p.getPreco()),
                p.getCategoria(),
                p.getEstoqueP()
        };
            tabela.addRow(linha);
        }
        return tabela;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ConsultaProduto().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TFpesquisar;
    private javax.swing.JButton VoltarJB;
    private javax.swing.JButton atualizarJB;
    private javax.swing.JButton cadastrarJB;
    private javax.swing.JButton excluirJB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton pesquisarJB;
    // End of variables declaration//GEN-END:variables
}
