/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Usuario;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;

/**
 *
 * @author kikut
 */
public class Menu extends javax.swing.JFrame {
    
    private Usuario usuarioLogado; 

    public Menu(Usuario usuarioLogado) {
        initComponents();
        
        this.usuarioLogado = usuarioLogado; 
        
        if (usuarioLogado == null || usuarioLogado.getCargo() == null) {
            return;
        }

        if (usuarioLogado.getCargo().equalsIgnoreCase("Gerente")) {
            UsuarioJB.setEnabled(true);
            ProdutoJB.setEnabled(true);
            MateriaPrimaJB.setEnabled(true);
            ClienteJB.setEnabled(true);
            CaixaJB.setEnabled(true);
        } else if (usuarioLogado.getCargo().equalsIgnoreCase("Artista")) {
            UsuarioJB.setEnabled(false);
            ProdutoJB.setEnabled(true);
            MateriaPrimaJB.setEnabled(true);
            ClienteJB.setEnabled(true);
            CaixaJB.setEnabled(true);
        } else {
            UsuarioJB.setEnabled(false);
            ProdutoJB.setEnabled(true);
            MateriaPrimaJB.setEnabled(false);
            ClienteJB.setEnabled(true);
            CaixaJB.setEnabled(true);
        }
    }
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());
    
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        
    }
    
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel();
        jLabel1 = new JLabel();
        UsuarioJB = new JButton();
        ProdutoJB = new JButton();
        MateriaPrimaJB = new JButton();
        ClienteJB = new JButton();
        CaixaJB = new JButton();
        jButton6 = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new Color(68, 68, 68));

        jLabel1.setFont(new Font("Microsoft YaHei UI Light", 0, 36)); // NOI18N
        jLabel1.setForeground(new Color(247, 247, 247));
        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel1.setText("MENU");

        UsuarioJB.setBackground(new Color(56, 56, 56));
        UsuarioJB.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        UsuarioJB.setForeground(new Color(247, 247, 247));
        UsuarioJB.setText("Usuário");
        UsuarioJB.addActionListener(this::UsuarioJBActionPerformed);

        ProdutoJB.setBackground(new Color(56, 56, 56));
        ProdutoJB.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        ProdutoJB.setForeground(new Color(247, 247, 247));
        ProdutoJB.setText("Produto");
        ProdutoJB.addActionListener(this::ProdutoJBActionPerformed);

        MateriaPrimaJB.setBackground(new Color(56, 56, 56));
        MateriaPrimaJB.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        MateriaPrimaJB.setForeground(new Color(247, 247, 247));
        MateriaPrimaJB.setText("Matéria Prima");
        MateriaPrimaJB.addActionListener(this::MateriaPrimaJBActionPerformed);

        ClienteJB.setBackground(new Color(56, 56, 56));
        ClienteJB.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        ClienteJB.setForeground(new Color(247, 247, 247));
        ClienteJB.setText("Cliente");
        ClienteJB.addActionListener(this::ClienteJBActionPerformed);

        CaixaJB.setBackground(new Color(56, 56, 56));
        CaixaJB.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        CaixaJB.setForeground(new Color(247, 247, 247));
        CaixaJB.setText("Caixa");
        CaixaJB.addActionListener(this::CaixaJBActionPerformed);

        jButton6.setBackground(new Color(102, 0, 0));
        jButton6.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        jButton6.setForeground(new Color(255, 153, 153));
        jButton6.setText("Voltar");
        jButton6.addActionListener(this::jButton6ActionPerformed);

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jButton6, GroupLayout.PREFERRED_SIZE, 140, GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(ProdutoJB, GroupLayout.PREFERRED_SIZE, 160, GroupLayout.PREFERRED_SIZE)
                            .addComponent(UsuarioJB, GroupLayout.PREFERRED_SIZE, 160, GroupLayout.PREFERRED_SIZE)
                            .addComponent(MateriaPrimaJB, GroupLayout.PREFERRED_SIZE, 160, GroupLayout.PREFERRED_SIZE)
                            .addComponent(ClienteJB, GroupLayout.PREFERRED_SIZE, 160, GroupLayout.PREFERRED_SIZE)
                            .addComponent(CaixaJB, GroupLayout.PREFERRED_SIZE, 160, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(UsuarioJB)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ProdutoJB)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MateriaPrimaJB)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ClienteJB)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CaixaJB)
                .addGap(26, 26, 26)
                .addComponent(jButton6)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ClienteJBActionPerformed(ActionEvent evt) {//GEN-FIRST:event_ClienteJBActionPerformed
        ConsultaCliente cc = new ConsultaCliente(this.usuarioLogado);
        cc.setVisible(true);
    }//GEN-LAST:event_ClienteJBActionPerformed

    private void UsuarioJBActionPerformed(ActionEvent evt) {//GEN-FIRST:event_UsuarioJBActionPerformed
        ConsultaUsuario cu = new ConsultaUsuario();
        cu.setVisible(true);
    }//GEN-LAST:event_UsuarioJBActionPerformed

    private void ProdutoJBActionPerformed(ActionEvent evt) {//GEN-FIRST:event_ProdutoJBActionPerformed
        ConsultaProduto c = new ConsultaProduto(this.usuarioLogado);
    
        c.setVisible(true);
    }//GEN-LAST:event_ProdutoJBActionPerformed

    private void MateriaPrimaJBActionPerformed(ActionEvent evt) {//GEN-FIRST:event_MateriaPrimaJBActionPerformed
        ConsultaMateriaPrima cm = new ConsultaMateriaPrima(this.usuarioLogado);
        cm.setVisible(true);
    }//GEN-LAST:event_MateriaPrimaJBActionPerformed

    private void CaixaJBActionPerformed(ActionEvent evt) {//GEN-FIRST:event_CaixaJBActionPerformed
        CaixaView c= new CaixaView(this.usuarioLogado);
        c.setVisible(true);
    }//GEN-LAST:event_CaixaJBActionPerformed

    private void jButton6ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton CaixaJB;
    private JButton ClienteJB;
    private JButton MateriaPrimaJB;
    private JButton ProdutoJB;
    private JButton UsuarioJB;
    private JButton jButton6;
    private JLabel jLabel1;
    private JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
